version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/smart-contracts"
    schedule:
      interval: "weekly" # Monday
    target-branch: "main"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly" # Monday
    target-branch: "main"